index:
    path: /
    controller: App\Controller\IndexController::index
admin:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index
login:
    path:       /login
    controller: App\Controller\Security\SecurityController::login